version: 1.0.{build}

image: Visual Studio 2017 Preview

branches:
  only:
    - master
    - ci-appveyor # TODO: remove

clone_folder: c:\game

before_build:
  - cmd: mkdir c:\game-build
  - cmd: mkdir c:\tmp
  - cmd: cd c:\tmp
  - ps: Start-FileDownload 'https://downloads.tuxfamily.org/godotengine/3.0.2/Godot_v3.0.2-stable_win64.exe.zip' -FileName godot.zip
  - cmd: 7z x godot.zip
  - ps: mv Godot_v3.0.2-stable_win64.exe godot.exe

build_script:
  - cmd: godot.exe --no-window --export 'HTML5' --path c:\game c:\game-build\index.html

artifacts:
  - path: c:\game-build

deploy:
  - provider: GitHub
    artifact:
    draft: false
    prerelease: false
    on:
      branch: master
      appveyor_repo_tag: true # deploy on tag push only
