version: 1.0.{build}

branches:
  only:
    - master
    - ci-appveyor # TODO: remove

clone_folder: c:\game

platform: x64
image: Visual Studio 2017

# https://www.appveyor.com/docs/how-to/rdp-to-build-worker/
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

before_build:
  - ps: mkdir c:\game-build\windows
  - ps: mkdir c:\game-build\linux
  - ps: mkdir c:\game-build\mac
  - ps: mkdir c:\game-build\html
  - ps: mkdir c:\game-tmp
  - ps: cd c:\game-tmp
  # Install OpenGL 3
  - ps: Start-FileDownload 'https://sourceforge.net/projects/msys2/files/REPOS/MINGW/x86_64/mingw-w64-x86_64-mesa-17.0.0-1-any.pkg.tar.xz/download' -fileName opengl.tar.xz
  - ps: 7z x opengl.tar.xz
  - ps: 7z x opengl.tar
  - ps: mv mingw64/bin/* .
  # Install Godot
  - ps: Start-FileDownload 'https://downloads.tuxfamily.org/godotengine/3.0.2/Godot_v3.0.2-stable_win64.exe.zip'
  - ps: 7z x Godot_v3.0.2-stable_win64.exe.zip
  - ps: mv Godot_v3.0.2-stable_win64.exe godot.exe
  # Install Godot export templates
  - ps: Start-FileDownload 'https://downloads.tuxfamily.org/godotengine/3.0.2/Godot_v3.0.2-stable_export_templates.tpz'
  - ps: 7z x Godot_v3.0.2-stable_export_templates.tpz
  - ps: mkdir        C:\Users\appveyor\AppData\Roaming\Godot\templates
  - ps: mv templates C:\Users\appveyor\AppData\Roaming\Godot\templates\3.0.2.stable

build_script:
  - cmd: godot.exe --no-window --path c:\game --export "Windows Desktop" c:\game-build\windows\game.exe
  - cmd: godot.exe --no-window --path c:\game --export "Linux/X11"       c:\game-build\linux\game
  - cmd: godot.exe --no-window --path c:\game --export "Mac OSX"         c:\game-build\mac\game
  - cmd: godot.exe --no-window --path c:\game --export "HTML5"           c:\game-build\html\game.html

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

artifacts:
  - path: c:\game-build\windows
  - path: c:\game-build\linux
  - path: c:\game-build\mac
  - path: c:\game-build\html

deploy:
  - provider: GitHub
    artifact: windows|linux|mac
    draft: false
    prerelease: false
    on:
      appveyor_repo_tag: true # deploy on tag push only
