version: 1.0.{build}

branches:
  only:
    - master
    - ci-appveyor # TODO: remove

clone_folder: c:\game

platform: x64
image: Visual Studio 2017

# https://www.appveyor.com/docs/how-to/rdp-to-build-worker/
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

before_build:
  - cmd: mkdir c:\game-build
  - cmd: mkdir c:\game-tmp
  - cmd: cd c:\game-tmp
  # Install OpenGL 3
  - ps: Start-FileDownload 'https://sourceforge.net/projects/msys2/files/REPOS/MINGW/x86_64/mingw-w64-x86_64-mesa-17.0.0-1-any.pkg.tar.xz/download' -fileName opengl.tar.xz
  - cmd: 7z x opengl.tar.xz
  - cmd: 7z x opengl.tar
  - ps: mv mingw64/bin/* .
  # Install Godot
  - ps: Start-FileDownload 'https://downloads.tuxfamily.org/godotengine/3.0.2/Godot_v3.0.2-stable_win64.exe.zip'
  - cmd: 7z x Godot_v3.0.2-stable_win64.exe.zip
  - ps: mv Godot_v3.0.2-stable_win64.exe godot.exe

build_script:
  - cmd: godot.exe --no-window --export "Windows Desktop" --path c:\game c:\game-build\game.exe

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

artifacts:
  - path: c:\game-build

deploy:
  - provider: GitHub
    artifact:
    draft: false
    prerelease: false
    on:
      branch: master
      appveyor_repo_tag: true # deploy on tag push only
